ARG ARCH=frommakefile
ARG DOCKERSRC=frommakefile
ARG USERNAME=frommakefile
#
FROM ${USERNAME}/${DOCKERSRC}:${ARCH}
#
ARG PUID=1000
ARG PGID=1000
#
RUN set -xe \
    && addgroup -g ${PGID} -S alpine \
    && adduser -u ${PUID} -G alpine -H -D alpine \
    && apk add --no-cache --purge -uU \
    apache2-utils \
    logrotate \
    nginx \
    openssl \
    && rm -rf /var/cache/apk/* /tmp/*
# add local files
COPY root/ /
# ports
EXPOSE 80 443
# volumes
VOLUME /config/ /storage/
#
ENTRYPOINT ["/init"]
