#!/usr/bin/with-contenv bash
set -e

vecho () { if [ "${S6_VERBOSITY:-1}" -gt 0 ]; then echo "[$0] $@"; fi; }

ROOTDIR="${ROOTDIR:-/config}";
KEYDIR="${KEYDIR:-$ROOTDIR/keys}";
PKEYFILE="${PKEYFILE:-$KEYDIR/private.key}";
CERTFILE="${CERTFILE:-$KEYDIR/certificate.crt}";
DEFAULTSUBJECT="/C=US/ST=NY/L=EXAMPLE/O=EXAMPLE/OU=EXAMPLE/CN=*/emailAddress=me@example.com"
SSLSUBJECT=${SSLSUBJECT:-$DEFAULTSUBJECT};

if [ -z "${NGINX_NO_HTTPS}" ]; # i.e. no need for certificate
then
    if [ -n "${NGINX_NO_CERTGEN}" ]; # set to 'true' to skip generating certs
    then
        vecho "Not generating certfile/key.";
    elif [ -f "${PKEYFILE}" ] && [ -f "${CERTFILE}" ];
    then
        vecho "Using cert found in ${CERTFILE}";
        vecho "Using key  found in ${PKEYFILE}";
        vecho "Make sure nginx configurations have the same path as these.";
    else
        vecho "Generating self-signed cert/key in";
        vecho "${CERTFILE} / ${PKEYFILE}";
        vecho "You may want to replace these with your own.";
        openssl req -newkey rsa:4096 -x509 -days 3650 -nodes -out "${CERTFILE}" -keyout "${PKEYFILE}" -subj "$SSLSUBJECT";
    fi;
# else
#     vecho "Not generating certificates";
fi;

HTPASSWDFILE="${HTPASSWDFILE:-$KEYDIR/.htpasswd}";
ADMIN=${WEBADMIN:-admin};
PASSWORD=${PASSWORD:-insecurebydefault};

if [ -z "${NGINX_NO_HTPASSWD}" ]; # i.e. no need for htpasswd
then
    if [ -f "${HTPASSWDFILE}" ];
    then
        vecho "Using .htpasswd found in ${HTPASSWDFILE}";
    else
        vecho "Generating ${HTPASSWDFILE}";
        vecho "Adding credentials for ${ADMIN}";
        htpasswd -bcB "${HTPASSWDFILE}" "${ADMIN}" "${PASSWORD}";
    fi;
# else
#     vecho "Not generating .htpasswd";
fi;

