#!/usr/bin/with-contenv bash

echo 'fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;' >> /etc/nginx/fastcgi_params
# remove default conf
rm -f /etc/nginx/conf.d/default.conf
# fix logrotate
sed -i "s#/var/log/messages {}.*# #g" /etc/logrotate.conf

# make our folders
mkdir -p \
	/config/{nginx/site-confs,www,log/nginx,keys} \
	/run \
	/var/lib/nginx/tmp/client_body

# copy config files
[[ ! -f /config/nginx/nginx.conf ]] && \
	cp /defaults/nginx.conf /config/nginx/nginx.conf
[[ $(find /config/nginx/site-confs -type f | wc -l) -eq 0 ]] && \
	cp /defaults/default /config/nginx/site-confs/default
[[ $(find /config/www -type f | wc -l) -eq 0 ]] && \
	cp /defaults/index.html /config/www/index.html

# permissions
chown -R alpine:alpine \
	/config \
	/run \
	/var/lib/nginx
chmod -R g+w /config/{nginx,www,log}
chmod -R 644 /etc/logrotate.d /config/log
