#!/usr/bin/with-contenv bash
KEYDIR="/config/keys";

SUBJECT="/C=US/ST=NY/L=EXAMPLE/O=EXAMPLE/OU=WOAHBase/CN=*/emailAddress=everybodycanseethis@mailinator.com"
SSLSUBJECT=${SSLSUBJECT:-$SUBJECT};

ADMIN=${WEBADMIN:-admin}
PASSWORD=${PASSWORD:-insecurebydefault}

if [[ -f ${KEYDIR}/privatekey.pem && -f ${KEYDIR}/certificate.crt ]]; then
    echo "using keys found in /config/keys"
else
    echo "generating self-signed keys in ${KEYDIR}, you can replace these with your own keys if required";
    openssl req -newkey rsa:4096 -x509 -days 3650 -nodes -out ${KEYDIR}/certificate.crt -keyout ${KEYDIR}/privatekey.pem -subj "$SUBJECT";
fi

if [ -f ${KEYDIR}/.htpasswd ];
then
    echo "using .htpasswd found in /config/keys";
else
    echo "generatign .htpasswd in /config/keys";
    echo "adding credentials: ${ADMIN}/${PASSWORD}";
    htpasswd -bcB ${KEYDIR}/.htpasswd ${ADMIN} ${PASSWORD}
fi;

